### PR TITLE
Support decoding Network Specific Number

### PR DESCRIPTION
**Pull request by spcbowen**

### CODE REVIEW

**Review by mgaman — COMMENTED** [review]
Please give me an example of a Network Specific Address. I've never really investigated that topic and am reluctant to merge your change until I understand it more/

**Comment by spcbowen** [comment]
In order to check my credit balance on my network, I need to send a text to "669". In response I get a text from "669" with my current package and remaining balance. The FROM address in this response has type-of-address 3, which according to the spec at https://www.etsi.org/deliver/etsi_gts/03/0340/05.03.00_60/gsmts_0340v050300p.pdf (page 33) means "Network specific number".

Treating it the same as type 2 (National number) works for my case, but without explicit support for type 3 PDUlib fails to decode the message.

Here's an example PDU: 07914497857889050403B166F90000228062122362401CD9771D840EDBCB20F71BD40ED3C7E8B4FB0C12D7DD6476790E

**Comment by mgaman** [comment]
Interesting, I need to look further into this.
Does your example above work both at home and when roaming? Does it assume
a service center in the same country?
As you can see I have to cover all bases before merging changes. Please be
patient while I check it out.

**Comment by spcbowen** [comment]
I haven't tested it while roaming, and won't be able to any time in the near future.
I don't think it is related to a service center at all... it's just a number which only has meaning on "your" network.
No rush from my point of view... it's working for my use case.

**Comment by mgaman** [comment]
I have not found a way to verify the changes so I am reluctant to approve a pull request that I have not tested.
However I am updating README.md highlighting the issue and showing your source change, This I have modified to
old
case 2:
new
case 2:
[[fallthrough]];
case 3:

**Pull request closed without merging**
